CREATE TABLE genres (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    CONSTRAINT uk_genres_name UNIQUE (name)
);

CREATE TABLE books (
    id UUID PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    description VARCHAR(1000),
    release_year INTEGER NOT NULL,
    cover_url VARCHAR(255),
    author VARCHAR(255) NOT NULL,
    isbn VARCHAR(255) NOT NULL,
    page_count INTEGER NOT NULL,
    publisher VARCHAR(255) NOT NULL,
    version BIGINT NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE,
    deleted_at TIMESTAMP(6) WITH TIME ZONE
);

CREATE TABLE book_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255),
    description VARCHAR(1000),
    release_year INTEGER NOT NULL,
    cover_url VARCHAR(255),
    author VARCHAR(255) NOT NULL,
    isbn VARCHAR(255) NOT NULL,
    page_count INTEGER NOT NULL,
    publisher VARCHAR(255) NOT NULL,
    version BIGINT NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE,
    deleted_at TIMESTAMP(6) WITH TIME ZONE
);

CREATE TABLE book_genre_id (
    book_id UUID NOT NULL,
    genre_id BIGINT NOT NULL,
    PRIMARY KEY (book_id, genre_id),
    CONSTRAINT fk_book_genre_id_book_id
        FOREIGN KEY (book_id) REFERENCES books (id),
    CONSTRAINT fk_book_genre_id_genre_id
        FOREIGN KEY (genre_id) REFERENCES genres (id)
);

CREATE TABLE book_request_genre_id (
    book_request_id BIGINT NOT NULL,
    genre_id BIGINT NOT NULL,
    PRIMARY KEY (book_request_id, genre_id),
    CONSTRAINT fk_book_request_genre_id_request_id
        FOREIGN KEY (book_request_id) REFERENCES book_requests (id),
    CONSTRAINT fk_book_request_genre_id_genre_id
        FOREIGN KEY (genre_id) REFERENCES genres (id)
);

CREATE TABLE book_progress (
    id UUID PRIMARY KEY,
    book_id UUID NOT NULL,
    user_id UUID NOT NULL,
    reading_status VARCHAR(255) NOT NULL,
    current_page INTEGER NOT NULL,
    started_at TIMESTAMP(6) WITH TIME ZONE,
    end_at TIMESTAMP(6) WITH TIME ZONE,
    is_active BOOLEAN NOT NULL,
    CONSTRAINT fk_book_progress_book_id
        FOREIGN KEY (book_id) REFERENCES books (id)
);

CREATE TABLE book_lists (
    id UUID PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    description VARCHAR(255) NOT NULL,
    type VARCHAR(255) NOT NULL,
    user_owner UUID NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL
);

CREATE TABLE book_list_books (
    book_list_id UUID NOT NULL,
    book_id UUID NOT NULL,
    PRIMARY KEY (book_list_id, book_id),
    CONSTRAINT fk_book_list_books_list_id
        FOREIGN KEY (book_list_id) REFERENCES book_lists (id),
    CONSTRAINT fk_book_list_books_book_id
        FOREIGN KEY (book_id) REFERENCES books (id)
);

CREATE TABLE book_list_memberships (
    id UUID PRIMARY KEY,
    book_list_id UUID,
    user_id UUID NOT NULL,
    role VARCHAR(255),
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_book_list_memberships_list_id
        FOREIGN KEY (book_list_id) REFERENCES book_lists (id)
);

CREATE TABLE book_list_likes (
    id UUID PRIMARY KEY,
    book_list_id UUID,
    user_id UUID,
    CONSTRAINT fk_book_list_likes_list_id
        FOREIGN KEY (book_list_id) REFERENCES book_lists (id)
);

CREATE INDEX idx_book_progress_user_id ON book_progress (user_id);
CREATE INDEX idx_book_progress_book_id ON book_progress (book_id);
CREATE INDEX idx_book_lists_user_owner ON book_lists (user_owner);
CREATE INDEX idx_book_list_memberships_user_id ON book_list_memberships (user_id);
CREATE INDEX idx_book_list_likes_user_id ON book_list_likes (user_id);

INSERT INTO genres (name)
VALUES
    (U&'Fic\00E7\00E3o Cient\00EDfica'),
    ('Fantasia'),
    ('Terror'),
    ('Romance'),
    ('Suspense'),
    ('Biografia'),
    (U&'Hist\00F3ria'),
    ('Autoajuda'),
    ('Distopia'),
    ('Aventura');
