spring.application.name=catalog-service

server.port=${SERVER_PORT:8080}

# CORS Configuration
app.cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:3000,http://localhost:3001}
spring.profiles.active=local

# Upload Configuration

app.upload.books-dir=./uploads/books

management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always
management.endpoint.health.probes.enabled=true
management.health.livenessState.enabled=true
management.health.readinessState.enabled=true
management.health.kafka.enabled=true
management.prometheus.metrics.export.enabled=true
management.metrics.tags.service=${spring.application.name}

logging.structured.format.console=logstash
logging.structured.json.add.service=${spring.application.name}
logging.structured.json.add.environment=${VELLUM_ENVIRONMENT:local}
logging.structured.json.rename.logger_name=logger

spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS}
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.properties.spring.json.add.type.headers=true

spring.kafka.producer.properties.spring.json.type.mapping=\
  create_book_event:com.vellumhub.kafka.contracts.book.CreateBookEvent,\
  update_book_event:com.vellumhub.kafka.contracts.book.UpdateBookEvent,\
  delete_book_event:com.vellumhub.kafka.contracts.book.DeleteBookEvent, \
  update_book_progress_event:com.vellumhub.kafka.contracts.readingprogress.UpdateBookProgressEvent, \
  create_book_progress_event:com.vellumhub.kafka.contracts.readingprogress.CreateBookProgressEvent
