apiVersion: apps/v1
kind: Deployment
metadata: {name: gateway-service}
spec: {replicas: 1}
---
apiVersion: apps/v1
kind: Deployment
metadata: {name: user-service}
spec: {replicas: 1}
---
apiVersion: apps/v1
kind: Deployment
metadata: {name: catalog-service}
spec: {replicas: 1}
---
apiVersion: apps/v1
kind: Deployment
metadata: {name: engagement-service}
spec: {replicas: 1}
---
apiVersion: apps/v1
kind: Deployment
metadata: {name: recommendation-service}
spec: {replicas: 1}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata: {name: default-deny}
$patch: delete
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata: {name: allow-dns}
$patch: delete
