server:
  port: 8080

logging:
  level:
    org.springframework.cloud.gateway: TRACE

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: user
              uri: ${USER_SERVICE_URL:http://user-service:8080}
              predicates:
                - Path=/api/v1/users/**
              filters:
                - StripPrefix=2
                - name: RequestRateLimiter
                  args:
                    key-resolver: "#{@ipKeyResolver}"
                    redis-rate-limiter.replenishRate: 5
                    redis-rate-limiter.burstCapacity: 10

            - id: auth
              uri: ${USER_SERVICE_URL:http://user-service:8080}
              predicates:
                - Path=/api/v1/auth/**
              filters:
                - StripPrefix=2
                - name: RequestRateLimiter
                  args:
                    key-resolver: "#{@ipKeyResolver}"
                    redis-rate-limiter.replenishRate: 5
                    redis-rate-limiter.burstCapacity: 10



            - id: catalogs
              uri: ${CATALOG_SERVICE_URL:http://catalog-service:8080}
              predicates:
                - Path=/api/v1/**
              filters:
                - StripPrefix=2
                - name: RequestRateLimiter
                  args:
                    key-resolver: "#{@userKeyResolver}"
                    redis-rate-limiter.replenishRate: 30
                    redis-rate-limiter.burstCapacity: 60

            - id: engagements
              uri: ${ENGAGEMENT_SERVICE_URL:http://engagement-service:8080}
              predicates:
                - Path=/api/v1/**
              filters:
                - StripPrefix=2
                - name: RequestRateLimiter
                  args:
                    key-resolver: "#{@userKeyResolver}"
                    redis-rate-limiter.replenishRate: 30
                    redis-rate-limiter.burstCapacity: 60

            - id: recommendations
              uri: ${RECOMMENDATION_SERVICE_URL:http://recommendation-service:8080}
              predicates:
                - Path=/api/v1/**
              filters:
                - StripPrefix=2
                - name: RequestRateLimiter
                  args:
                    key-resolver: "#{@userKeyResolver}"
                    redis-rate-limiter.replenishRate: 20
                    redis-rate-limiter.burstCapacity: 40

  security:
    oauth2:
      resourceserver:
        jwt:
          secret-key: ${JWT_KEY:dasdasidaidIHDASOHDOASHDPHAsdhashdouahsoduahsoduaoudhaoudhohdouashd}

  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: ${SPRING_DATA_REDIS_PORT:6379}
      connect-timeout: 2s



management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics,prometheus"
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true
    kafka:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true