spring.application.name=recommendation-service

# CORS Configuration
app.cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:3000,http://localhost:3001}

spring.profiles.active=local

server.port=${SERVER_PORT:8085}

feign.client.config.default.connectTimeout=5000
feign.client.config.default.readTimeout=5000
catalog-service.ribbon.listOfServers=http://catalog-service:8080

management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always
management.endpoint.health.probes.enabled=true
management.health.livenessState.enabled=true
management.health.readinessState.enabled=true
management.health.kafka.enabled=true
management.prometheus.metrics.export.enabled=true
management.metrics.tags.service=${spring.application.name}

logging.structured.format.console=logstash
logging.structured.json.add.service=${spring.application.name}
logging.structured.json.add.environment=${VELLUM_ENVIRONMENT:local}
logging.structured.json.rename.logger_name=logger

spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS}

spring.kafka.consumer.group-id=recommendation-group
spring.kafka.consumer.auto-offset-reset=earliest

spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer

spring.kafka.consumer.properties.spring.deserializer.value.delegate.class=org.springframework.kafka.support.serializer.JsonDeserializer

spring.kafka.consumer.properties.spring.json.type.mapping=\
  create_book_event:com.vellumhub.kafka.contracts.book.CreateBookEvent,\
  update_book_event:com.vellumhub.kafka.contracts.book.UpdateBookEvent,\
  delete_book_event:com.vellumhub.kafka.contracts.book.DeleteBookEvent,\
  create_rating_event:com.vellumhub.kafka.contracts.engagement.CreatedRatingEvent, \
  update_book_progress_event:com.vellumhub.kafka.contracts.readingprogress.UpdateBookProgressEvent, \
  create_book_progress_event:com.vellumhub.kafka.contracts.readingprogress.CreateBookProgressEvent, \
  reaction_changed_event:com.vellumhub.kafka.contracts.engagement.ReactionChangedEvent, \
  created_user_preference:com.vellumhub.kafka.contracts.user.CreateUserPreferenceEvent

spring.kafka.consumer.properties.spring.json.trusted.packages=*
