CREATE SEQUENCE reactions_seq START WITH 1 INCREMENT BY 50;

CREATE TABLE book_snapshot (
    book_id UUID PRIMARY KEY
);

CREATE TABLE rating (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL,
    book_id UUID NOT NULL,
    stars INTEGER NOT NULL,
    review VARCHAR(1000),
    timestamp TIMESTAMP(6) WITHOUT TIME ZONE
);

CREATE TABLE reactions (
    id BIGINT PRIMARY KEY,
    user_id UUID NOT NULL,
    book_snapshot_id UUID,
    type_reaction VARCHAR(255) NOT NULL,
    CONSTRAINT fk_reactions_book_snapshot_id
        FOREIGN KEY (book_snapshot_id) REFERENCES book_snapshot (book_id)
);

CREATE TABLE reading_session_entries (
    id BIGINT PRIMARY KEY,
    reading_session_id UUID,
    user_id UUID NOT NULL,
    page_read INTEGER NOT NULL,
    book_snapshot_book_id UUID,
    type VARCHAR(255),
    timestamp TIMESTAMP(6) WITH TIME ZONE,
    CONSTRAINT fk_reading_session_entries_book_snapshot_book_id
        FOREIGN KEY (book_snapshot_book_id) REFERENCES book_snapshot (book_id)
);

CREATE INDEX idx_rating_user_id ON rating (user_id);
CREATE INDEX idx_rating_book_id ON rating (book_id);
CREATE INDEX idx_reactions_user_id ON reactions (user_id);
CREATE INDEX idx_reading_session_entries_user_id ON reading_session_entries (user_id);
