spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          secret-key: ${JWT_KEY}

management:
  endpoint:
    health:
      show-details: never

logging:
  level:
    org.springframework.cloud.gateway: INFO
