

apiVersion: 1

deleteDatasources:
  - name: Prometheus
    orgId: 1
  - name: Loki
    orgId: 1
  - name: Tempo
    orgId: 1

prune: true

datasources:
  - name: Prometheus
    uid: prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: http://prometheus:9090
    isDefault: true
    editable: true

  - name: Loki
    uid: loki
    type: loki
    access: proxy
    orgId: 1
    url: http://loki:3100
    editable: true
    jsonData:
      maxLines: 1000

  - name: Tempo
    uid: tempo
    type: tempo
    access: proxy
    orgId: 1
    url: http://tempo:3200
    editable: true
    jsonData:
      tracesToLogsV2:
        datasourceUid: loki
        tags:
          - key: service.name
            value: service
        filterByTraceID: true
        filterBySpanID: true
      serviceMap:
        datasourceUid: prometheus
